<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/04/29 12:19:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
